//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.18 at 12:05:10 PM CET 
//


package net.opengis.swe;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AbstractEncodingPropertyByValueType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractEncodingPropertyByValueType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opengis.net/swe/2.0}AbstractEncoding"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractEncodingPropertyByValueType", propOrder = {
    "abstractEncoding"
})
public abstract class AbstractEncodingPropertyByValueType {

    @XmlElementRef(name = "AbstractEncoding", namespace = "http://www.opengis.net/swe/2.0", type = JAXBElement.class)
    protected JAXBElement<? extends AbstractEncodingType> abstractEncoding;

    /**
     * Gets the value of the abstractEncoding property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AbstractEncodingType }{@code >}
     *     {@link JAXBElement }{@code <}{@link BinaryEncodingType }{@code >}
     *     {@link JAXBElement }{@code <}{@link TextEncodingType }{@code >}
     *     {@link JAXBElement }{@code <}{@link XMLEncodingType }{@code >}
     *     
     */
    public JAXBElement<? extends AbstractEncodingType> getAbstractEncoding() {
        return abstractEncoding;
    }

    /**
     * Sets the value of the abstractEncoding property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AbstractEncodingType }{@code >}
     *     {@link JAXBElement }{@code <}{@link BinaryEncodingType }{@code >}
     *     {@link JAXBElement }{@code <}{@link TextEncodingType }{@code >}
     *     {@link JAXBElement }{@code <}{@link XMLEncodingType }{@code >}
     *     
     */
    public void setAbstractEncoding(JAXBElement<? extends AbstractEncodingType> value) {
        this.abstractEncoding = value;
    }

}
