//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.18 at 12:05:10 PM CET 
//


package net.opengis.swe;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TextEncodingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TextEncodingType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/swe/2.0}AbstractEncodingType">
 *       &lt;attribute name="collapseWhiteSpaces" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="decimalSeparator" type="{http://www.w3.org/2001/XMLSchema}string" default="." />
 *       &lt;attribute name="tokenSeparator" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="blockSeparator" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TextEncodingType")
public class TextEncodingType
    extends AbstractEncodingType
{

    @XmlAttribute(name = "collapseWhiteSpaces")
    protected Boolean collapseWhiteSpaces;
    @XmlAttribute(name = "decimalSeparator")
    protected String decimalSeparator;
    @XmlAttribute(name = "tokenSeparator", required = true)
    protected String tokenSeparator;
    @XmlAttribute(name = "blockSeparator", required = true)
    protected String blockSeparator;

    /**
     * Gets the value of the collapseWhiteSpaces property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isCollapseWhiteSpaces() {
        if (collapseWhiteSpaces == null) {
            return true;
        } else {
            return collapseWhiteSpaces;
        }
    }

    /**
     * Sets the value of the collapseWhiteSpaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCollapseWhiteSpaces(Boolean value) {
        this.collapseWhiteSpaces = value;
    }

    /**
     * Gets the value of the decimalSeparator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDecimalSeparator() {
        if (decimalSeparator == null) {
            return ".";
        } else {
            return decimalSeparator;
        }
    }

    /**
     * Sets the value of the decimalSeparator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDecimalSeparator(String value) {
        this.decimalSeparator = value;
    }

    /**
     * Gets the value of the tokenSeparator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTokenSeparator() {
        return tokenSeparator;
    }

    /**
     * Sets the value of the tokenSeparator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTokenSeparator(String value) {
        this.tokenSeparator = value;
    }

    /**
     * Gets the value of the blockSeparator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlockSeparator() {
        return blockSeparator;
    }

    /**
     * Sets the value of the blockSeparator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlockSeparator(String value) {
        this.blockSeparator = value;
    }

}
