//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.18 at 12:05:10 PM CET 
//


package net.opengis.sensorml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import net.opengis.swe.AbstractSWEIdentifiableType;
import net.opengis.swe.DataRecordPropertyType;
import net.opengis.swe.DataStreamPropertyType;


/**
 * <p>Java class for DataInterfaceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataInterfaceType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/swe/2.0}AbstractSWEIdentifiableType">
 *       &lt;sequence>
 *         &lt;element name="data" type="{http://www.opengis.net/swe/2.0}DataStreamPropertyType"/>
 *         &lt;element name="interfaceParameters" type="{http://www.opengis.net/swe/2.0}DataRecordPropertyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataInterfaceType", propOrder = {
    "data",
    "interfaceParameters"
})
public class DataInterfaceType
    extends AbstractSWEIdentifiableType
{

    @XmlElement(required = true)
    protected DataStreamPropertyType data;
    protected DataRecordPropertyType interfaceParameters;

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link DataStreamPropertyType }
     *     
     */
    public DataStreamPropertyType getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataStreamPropertyType }
     *     
     */
    public void setData(DataStreamPropertyType value) {
        this.data = value;
    }

    /**
     * Gets the value of the interfaceParameters property.
     * 
     * @return
     *     possible object is
     *     {@link DataRecordPropertyType }
     *     
     */
    public DataRecordPropertyType getInterfaceParameters() {
        return interfaceParameters;
    }

    /**
     * Sets the value of the interfaceParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataRecordPropertyType }
     *     
     */
    public void setInterfaceParameters(DataRecordPropertyType value) {
        this.interfaceParameters = value;
    }

}
