//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.18 at 12:05:10 PM CET 
//


package net.opengis.sensorml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PhysicalSystemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PhysicalSystemType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/sensorml/2.0}AbstractPhysicalProcessType">
 *       &lt;sequence>
 *         &lt;element name="components" type="{http://www.opengis.net/sensorml/2.0}ComponentListPropertyType" minOccurs="0"/>
 *         &lt;element name="connections" type="{http://www.opengis.net/sensorml/2.0}ConnectionListPropertyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PhysicalSystemType", propOrder = {
    "components",
    "connections"
})
public class PhysicalSystemType
    extends AbstractPhysicalProcessType
{

    protected ComponentListPropertyType components;
    protected ConnectionListPropertyType connections;

    /**
     * Gets the value of the components property.
     * 
     * @return
     *     possible object is
     *     {@link ComponentListPropertyType }
     *     
     */
    public ComponentListPropertyType getComponents() {
        return components;
    }

    /**
     * Sets the value of the components property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComponentListPropertyType }
     *     
     */
    public void setComponents(ComponentListPropertyType value) {
        this.components = value;
    }

    /**
     * Gets the value of the connections property.
     * 
     * @return
     *     possible object is
     *     {@link ConnectionListPropertyType }
     *     
     */
    public ConnectionListPropertyType getConnections() {
        return connections;
    }

    /**
     * Sets the value of the connections property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConnectionListPropertyType }
     *     
     */
    public void setConnections(ConnectionListPropertyType value) {
        this.connections = value;
    }

}
