//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.18 at 12:05:10 PM CET 
//


package net.opengis.sensorml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SimpleProcessType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SimpleProcessType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/sensorml/2.0}AbstractProcessType">
 *       &lt;sequence>
 *         &lt;element name="method" type="{http://www.opengis.net/sensorml/2.0}ProcessMethodPropertyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SimpleProcessType", propOrder = {
    "method"
})
public class SimpleProcessType
    extends AbstractProcessType
{

    protected ProcessMethodPropertyType method;

    /**
     * Gets the value of the method property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessMethodPropertyType }
     *     
     */
    public ProcessMethodPropertyType getMethod() {
        return method;
    }

    /**
     * Sets the value of the method property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessMethodPropertyType }
     *     
     */
    public void setMethod(ProcessMethodPropertyType value) {
        this.method = value;
    }

}
